// src/components/vue_pages/NewArticleForm.vue
<script lang="ts" setup>
import {Form, FormControl, FormField, FormItem, FormLabel} from '@/components/ui/vue/form'
import {Button} from '@/components/ui/vue/button'
import {Input} from '@/components/ui/vue/input'
import {useForm} from 'vee-validate'
import axios from 'axios'
import {useStore} from '@nanostores/vue'
import {$client} from '@/lib/stores.ts'
import * as z from "zod"
import {toTypedSchema} from '@vee-validate/zod'
import Editor from '@/components/new_text_editor/Editor.vue'

const {handleSubmit} = useForm()

axios.defaults.xsrfCookieName = 'csrftoken'
axios.defaults.withCredentials = false

const client = useStore($client)

const formSchema = z.object({
  title: z.string().max(100, {message: 'Title is too long'}),
  content: z.string(),
})

const form = useForm<z.infer<typeof formSchema>>({
  validationSchema: toTypedSchema(formSchema),
  initialValues: {
    title: '',
    content: '',
  }
})

const onSubmit = handleSubmit(values => {
  alert(JSON.stringify(values, null, 2))
})

// const onSubmit = async (values: z.infer<typeof formSchema>) => {
//   console.log(`values: ${JSON.stringify(values)}`)
//   await client.post(`/articles/`, {
//     title: values.title,
//     content: values.content
//   }, {
//     headers: {
//       'Authorization': `Token ${localStorage.getItem('token')}`
//     }
//   })
// }
</script>

<template>
  <main>
    <Form @submit="onSubmit">
      <FormField name="title" v-slot="{componentField}">
        <FormItem>
          <FormLabel>Title</FormLabel>
          <FormControl>
            <Input placeholder="Article title" v-bind="componentField" />
          </FormControl>
        </FormItem>
      </FormField>
      <div class="mt-10" />
      <FormField name="content" v-slot="{componentField}">
        <FormItem>
          <FormLabel>Content</FormLabel>
          <FormControl>
            <Editor />
          </FormControl>
        </FormItem>
      </FormField>
      <Button class="mt-4" variant="outline" type="submit">
        Post
      </Button>
    </Form>
  </main>
</template>

// src/components/react_pages/NewArticleForm.tsx
import {
    Form, FormControl, FormField, FormItem, FormLabel
} from '@/components/ui/form'
import {useForm} from 'react-hook-form'
import {zodResolver} from '@hookform/resolvers/zod'
import * as z from 'zod'
import {Input} from '@/components/ui/input.tsx'
import {useStore} from "@nanostores/react";
import {$client} from '@/lib/stores'
import {useState} from 'react'

import axios from 'axios'
import {Button} from "@/components/ui/button.tsx";
import {RichTextarea} from "@/components/ui/richtextarea.tsx";

export const NewArticleForm = () => {
    axios.defaults.xsrfCookieName = 'csrftoken';
    axios.defaults.withCredentials = false;

    const client = useStore($client)

    const formSchema = z.object({
        title: z.string().max(100, {message: 'Title is too long'}),
        content: z.string(),
    })

    const form = useForm<z.infer<typeof formSchema>>({
        resolver: zodResolver(formSchema),
        mode: 'onChange',
        defaultValues: {
            title: '',
            content: '',
        },
    })

    const onSubmit = async (values: z.infer<typeof formSchema>) => {
        console.log(`values: ${JSON.stringify(values)}`)
        await client.post(`/articles/`, {
            title: values.title,
            content: values.content
        }, {
            headers: {
                'Authorization': `Token ${localStorage.getItem('token')}`
            }
        })
    }

    return (
        <main>
            <Form {...form}>
                <form onSubmit={form.handleSubmit(onSubmit)}>
                    <FormField control={form.control} name='title' render={({field}) => (
                        <FormItem>
                            <FormLabel>Title</FormLabel>
                            <FormControl>
                                <Input placeholder='Article title' {...field} />
                            </FormControl>
                        </FormItem>
                    )}/>
                    <FormField control={form.control} name='content' render={({field}) => (
                        <FormItem>
                            <FormLabel>Content</FormLabel>
                            <FormControl>
                                <RichTextarea></RichTextarea>
                            </FormControl>
                        </FormItem>
                    )}/>
                    <Button className='mt-4' variant='outline' type='submit'>Post</Button>
                </form>
            </Form>
        </main>
    )
}
